// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewSendMsg.proto

#ifndef PROTOBUF_NewSendMsg_2eproto__INCLUDED
#define PROTOBUF_NewSendMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace com {
namespace tencent {
namespace mars {
namespace sample {
namespace proto {
class NewSendMsgRequest;
class NewSendMsgRequestDefaultTypeInternal;
extern NewSendMsgRequestDefaultTypeInternal _NewSendMsgRequest_default_instance_;
class NewSendMsgRequest_ChatInfo;
class NewSendMsgRequest_ChatInfoDefaultTypeInternal;
extern NewSendMsgRequest_ChatInfoDefaultTypeInternal _NewSendMsgRequest_ChatInfo_default_instance_;
class NewSendMsgRequest_ChatInfo_ToId;
class NewSendMsgRequest_ChatInfo_ToIdDefaultTypeInternal;
extern NewSendMsgRequest_ChatInfo_ToIdDefaultTypeInternal _NewSendMsgRequest_ChatInfo_ToId_default_instance_;
}  // namespace proto
}  // namespace sample
}  // namespace mars
}  // namespace tencent
}  // namespace com

namespace com {
namespace tencent {
namespace mars {
namespace sample {
namespace proto {

namespace protobuf_NewSendMsg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_NewSendMsg_2eproto

// ===================================================================

class NewSendMsgRequest_ChatInfo_ToId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId) */ {
 public:
  NewSendMsgRequest_ChatInfo_ToId();
  virtual ~NewSendMsgRequest_ChatInfo_ToId();

  NewSendMsgRequest_ChatInfo_ToId(const NewSendMsgRequest_ChatInfo_ToId& from);

  inline NewSendMsgRequest_ChatInfo_ToId& operator=(const NewSendMsgRequest_ChatInfo_ToId& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewSendMsgRequest_ChatInfo_ToId& default_instance();

  static inline const NewSendMsgRequest_ChatInfo_ToId* internal_default_instance() {
    return reinterpret_cast<const NewSendMsgRequest_ChatInfo_ToId*>(
               &_NewSendMsgRequest_ChatInfo_ToId_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NewSendMsgRequest_ChatInfo_ToId* other);

  // implements Message ----------------------------------------------

  inline NewSendMsgRequest_ChatInfo_ToId* New() const PROTOBUF_FINAL { return New(NULL); }

  NewSendMsgRequest_ChatInfo_ToId* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewSendMsgRequest_ChatInfo_ToId& from);
  void MergeFrom(const NewSendMsgRequest_ChatInfo_ToId& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewSendMsgRequest_ChatInfo_ToId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  friend struct protobuf_NewSendMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewSendMsgRequest_ChatInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo) */ {
 public:
  NewSendMsgRequest_ChatInfo();
  virtual ~NewSendMsgRequest_ChatInfo();

  NewSendMsgRequest_ChatInfo(const NewSendMsgRequest_ChatInfo& from);

  inline NewSendMsgRequest_ChatInfo& operator=(const NewSendMsgRequest_ChatInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewSendMsgRequest_ChatInfo& default_instance();

  static inline const NewSendMsgRequest_ChatInfo* internal_default_instance() {
    return reinterpret_cast<const NewSendMsgRequest_ChatInfo*>(
               &_NewSendMsgRequest_ChatInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NewSendMsgRequest_ChatInfo* other);

  // implements Message ----------------------------------------------

  inline NewSendMsgRequest_ChatInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  NewSendMsgRequest_ChatInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewSendMsgRequest_ChatInfo& from);
  void MergeFrom(const NewSendMsgRequest_ChatInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewSendMsgRequest_ChatInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef NewSendMsgRequest_ChatInfo_ToId ToId;

  // accessors -------------------------------------------------------

  // optional string content = 2;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
  bool has_toid() const;
  void clear_toid();
  static const int kToIdFieldNumber = 1;
  const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId& toid() const;
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* mutable_toid();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* release_toid();
  void set_allocated_toid(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* toid);

  // optional int32 Unknown2 = 3;
  bool has_unknown2() const;
  void clear_unknown2();
  static const int kUnknown2FieldNumber = 3;
  ::google::protobuf::int32 unknown2() const;
  void set_unknown2(::google::protobuf::int32 value);

  // optional int32 utc = 4;
  bool has_utc() const;
  void clear_utc();
  static const int kUtcFieldNumber = 4;
  ::google::protobuf::int32 utc() const;
  void set_utc(::google::protobuf::int32 value);

  // optional int32 Unknown3 = 5;
  bool has_unknown3() const;
  void clear_unknown3();
  static const int kUnknown3FieldNumber = 5;
  ::google::protobuf::int32 unknown3() const;
  void set_unknown3(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
 private:
  void set_has_toid();
  void clear_has_toid();
  void set_has_content();
  void clear_has_content();
  void set_has_unknown2();
  void clear_has_unknown2();
  void set_has_utc();
  void clear_has_utc();
  void set_has_unknown3();
  void clear_has_unknown3();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* toid_;
  ::google::protobuf::int32 unknown2_;
  ::google::protobuf::int32 utc_;
  ::google::protobuf::int32 unknown3_;
  friend struct protobuf_NewSendMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NewSendMsgRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.NewSendMsgRequest) */ {
 public:
  NewSendMsgRequest();
  virtual ~NewSendMsgRequest();

  NewSendMsgRequest(const NewSendMsgRequest& from);

  inline NewSendMsgRequest& operator=(const NewSendMsgRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NewSendMsgRequest& default_instance();

  static inline const NewSendMsgRequest* internal_default_instance() {
    return reinterpret_cast<const NewSendMsgRequest*>(
               &_NewSendMsgRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(NewSendMsgRequest* other);

  // implements Message ----------------------------------------------

  inline NewSendMsgRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  NewSendMsgRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewSendMsgRequest& from);
  void MergeFrom(const NewSendMsgRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewSendMsgRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef NewSendMsgRequest_ChatInfo ChatInfo;

  // accessors -------------------------------------------------------

  // optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 2;
  const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo& info() const;
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* mutable_info();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* release_info();
  void set_allocated_info(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* info);

  // required int32 cnt = 1;
  bool has_cnt() const;
  void clear_cnt();
  static const int kCntFieldNumber = 1;
  ::google::protobuf::int32 cnt() const;
  void set_cnt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.NewSendMsgRequest)
 private:
  void set_has_cnt();
  void clear_has_cnt();
  void set_has_info();
  void clear_has_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* info_;
  ::google::protobuf::int32 cnt_;
  friend struct protobuf_NewSendMsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NewSendMsgRequest_ChatInfo_ToId

// optional string id = 1;
inline bool NewSendMsgRequest_ChatInfo_ToId::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NewSendMsgRequest_ChatInfo_ToId::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NewSendMsgRequest_ChatInfo_ToId::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NewSendMsgRequest_ChatInfo_ToId::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& NewSendMsgRequest_ChatInfo_ToId::id() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  return id_.GetNoArena();
}
inline void NewSendMsgRequest_ChatInfo_ToId::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
#if LANG_CXX11
inline void NewSendMsgRequest_ChatInfo_ToId::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
#endif
inline void NewSendMsgRequest_ChatInfo_ToId::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
inline void NewSendMsgRequest_ChatInfo_ToId::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
inline ::std::string* NewSendMsgRequest_ChatInfo_ToId::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewSendMsgRequest_ChatInfo_ToId::release_id() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewSendMsgRequest_ChatInfo_ToId::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}

// -------------------------------------------------------------------

// NewSendMsgRequest_ChatInfo

// required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
inline bool NewSendMsgRequest_ChatInfo::has_toid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NewSendMsgRequest_ChatInfo::set_has_toid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NewSendMsgRequest_ChatInfo::clear_has_toid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NewSendMsgRequest_ChatInfo::clear_toid() {
  if (toid_ != NULL) toid_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::Clear();
  clear_has_toid();
}
inline const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId& NewSendMsgRequest_ChatInfo::toid() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  return toid_ != NULL ? *toid_
                         : *::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::internal_default_instance();
}
inline ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* NewSendMsgRequest_ChatInfo::mutable_toid() {
  set_has_toid();
  if (toid_ == NULL) {
    toid_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId;
  }
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  return toid_;
}
inline ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* NewSendMsgRequest_ChatInfo::release_toid() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  clear_has_toid();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* temp = toid_;
  toid_ = NULL;
  return temp;
}
inline void NewSendMsgRequest_ChatInfo::set_allocated_toid(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* toid) {
  delete toid_;
  toid_ = toid;
  if (toid) {
    set_has_toid();
  } else {
    clear_has_toid();
  }
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
}

// optional string content = 2;
inline bool NewSendMsgRequest_ChatInfo::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NewSendMsgRequest_ChatInfo::set_has_content() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NewSendMsgRequest_ChatInfo::clear_has_content() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NewSendMsgRequest_ChatInfo::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_content();
}
inline const ::std::string& NewSendMsgRequest_ChatInfo::content() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  return content_.GetNoArena();
}
inline void NewSendMsgRequest_ChatInfo::set_content(const ::std::string& value) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
#if LANG_CXX11
inline void NewSendMsgRequest_ChatInfo::set_content(::std::string&& value) {
  set_has_content();
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
#endif
inline void NewSendMsgRequest_ChatInfo::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
inline void NewSendMsgRequest_ChatInfo::set_content(const char* value, size_t size) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
inline ::std::string* NewSendMsgRequest_ChatInfo::mutable_content() {
  set_has_content();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewSendMsgRequest_ChatInfo::release_content() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  clear_has_content();
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewSendMsgRequest_ChatInfo::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    set_has_content();
  } else {
    clear_has_content();
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}

// optional int32 Unknown2 = 3;
inline bool NewSendMsgRequest_ChatInfo::has_unknown2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NewSendMsgRequest_ChatInfo::set_has_unknown2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NewSendMsgRequest_ChatInfo::clear_has_unknown2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NewSendMsgRequest_ChatInfo::clear_unknown2() {
  unknown2_ = 0;
  clear_has_unknown2();
}
inline ::google::protobuf::int32 NewSendMsgRequest_ChatInfo::unknown2() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown2)
  return unknown2_;
}
inline void NewSendMsgRequest_ChatInfo::set_unknown2(::google::protobuf::int32 value) {
  set_has_unknown2();
  unknown2_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown2)
}

// optional int32 utc = 4;
inline bool NewSendMsgRequest_ChatInfo::has_utc() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NewSendMsgRequest_ChatInfo::set_has_utc() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NewSendMsgRequest_ChatInfo::clear_has_utc() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NewSendMsgRequest_ChatInfo::clear_utc() {
  utc_ = 0;
  clear_has_utc();
}
inline ::google::protobuf::int32 NewSendMsgRequest_ChatInfo::utc() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.utc)
  return utc_;
}
inline void NewSendMsgRequest_ChatInfo::set_utc(::google::protobuf::int32 value) {
  set_has_utc();
  utc_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.utc)
}

// optional int32 Unknown3 = 5;
inline bool NewSendMsgRequest_ChatInfo::has_unknown3() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NewSendMsgRequest_ChatInfo::set_has_unknown3() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NewSendMsgRequest_ChatInfo::clear_has_unknown3() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NewSendMsgRequest_ChatInfo::clear_unknown3() {
  unknown3_ = 0;
  clear_has_unknown3();
}
inline ::google::protobuf::int32 NewSendMsgRequest_ChatInfo::unknown3() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown3)
  return unknown3_;
}
inline void NewSendMsgRequest_ChatInfo::set_unknown3(::google::protobuf::int32 value) {
  set_has_unknown3();
  unknown3_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown3)
}

// -------------------------------------------------------------------

// NewSendMsgRequest

// required int32 cnt = 1;
inline bool NewSendMsgRequest::has_cnt() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NewSendMsgRequest::set_has_cnt() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NewSendMsgRequest::clear_has_cnt() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NewSendMsgRequest::clear_cnt() {
  cnt_ = 0;
  clear_has_cnt();
}
inline ::google::protobuf::int32 NewSendMsgRequest::cnt() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.cnt)
  return cnt_;
}
inline void NewSendMsgRequest::set_cnt(::google::protobuf::int32 value) {
  set_has_cnt();
  cnt_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.cnt)
}

// optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
inline bool NewSendMsgRequest::has_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NewSendMsgRequest::set_has_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NewSendMsgRequest::clear_has_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NewSendMsgRequest::clear_info() {
  if (info_ != NULL) info_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::Clear();
  clear_has_info();
}
inline const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo& NewSendMsgRequest::info() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  return info_ != NULL ? *info_
                         : *::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::internal_default_instance();
}
inline ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* NewSendMsgRequest::mutable_info() {
  set_has_info();
  if (info_ == NULL) {
    info_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo;
  }
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  return info_;
}
inline ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* NewSendMsgRequest::release_info() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  clear_has_info();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* temp = info_;
  info_ = NULL;
  return temp;
}
inline void NewSendMsgRequest::set_allocated_info(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* info) {
  delete info_;
  info_ = info;
  if (info) {
    set_has_info();
  } else {
    clear_has_info();
  }
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace sample
}  // namespace mars
}  // namespace tencent
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NewSendMsg_2eproto__INCLUDED
