// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewSendMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "NewSendMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace tencent {
namespace mars {
namespace sample {
namespace proto {
class NewSendMsgRequest_ChatInfo_ToIdDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<NewSendMsgRequest_ChatInfo_ToId> {
} _NewSendMsgRequest_ChatInfo_ToId_default_instance_;
class NewSendMsgRequest_ChatInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<NewSendMsgRequest_ChatInfo> {
} _NewSendMsgRequest_ChatInfo_default_instance_;
class NewSendMsgRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<NewSendMsgRequest> {
} _NewSendMsgRequest_default_instance_;

namespace protobuf_NewSendMsg_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo_ToId, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo_ToId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo_ToId, id_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, toid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, unknown2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, utc_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest_ChatInfo, unknown3_),
  1,
  0,
  2,
  3,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest, cnt_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NewSendMsgRequest, info_),
  1,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(NewSendMsgRequest_ChatInfo_ToId)},
  { 7, 17, sizeof(NewSendMsgRequest_ChatInfo)},
  { 22, 29, sizeof(NewSendMsgRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_NewSendMsgRequest_ChatInfo_ToId_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_NewSendMsgRequest_ChatInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_NewSendMsgRequest_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "NewSendMsg.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _NewSendMsgRequest_ChatInfo_ToId_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _NewSendMsgRequest_ChatInfo_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _NewSendMsgRequest_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _NewSendMsgRequest_ChatInfo_ToId_default_instance_.DefaultConstruct();
  _NewSendMsgRequest_ChatInfo_default_instance_.DefaultConstruct();
  _NewSendMsgRequest_default_instance_.DefaultConstruct();
  _NewSendMsgRequest_ChatInfo_default_instance_.get_mutable()->toid_ = const_cast< ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId*>(
      ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::internal_default_instance());
  _NewSendMsgRequest_default_instance_.get_mutable()->info_ = const_cast< ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo*>(
      ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020NewSendMsg.proto\022\035com.tencent.mars.sam"
      "ple.proto\"\232\002\n\021NewSendMsgRequest\022\013\n\003cnt\030\001"
      " \002(\005\022G\n\004info\030\002 \001(\01329.com.tencent.mars.sa"
      "mple.proto.NewSendMsgRequest.ChatInfo\032\256\001"
      "\n\010ChatInfo\022L\n\004toId\030\001 \002(\0132>.com.tencent.m"
      "ars.sample.proto.NewSendMsgRequest.ChatI"
      "nfo.ToId\022\017\n\007content\030\002 \001(\t\022\020\n\010Unknown2\030\003 "
      "\001(\005\022\013\n\003utc\030\004 \001(\005\022\020\n\010Unknown3\030\005 \001(\005\032\022\n\004To"
      "Id\022\n\n\002id\030\001 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 334);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NewSendMsg.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_NewSendMsg_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NewSendMsgRequest_ChatInfo_ToId::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NewSendMsgRequest_ChatInfo_ToId::NewSendMsgRequest_ChatInfo_ToId()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_NewSendMsg_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
}
NewSendMsgRequest_ChatInfo_ToId::NewSendMsgRequest_ChatInfo_ToId(const NewSendMsgRequest_ChatInfo_ToId& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_id()) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  // @@protoc_insertion_point(copy_constructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
}

void NewSendMsgRequest_ChatInfo_ToId::SharedCtor() {
  _cached_size_ = 0;
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

NewSendMsgRequest_ChatInfo_ToId::~NewSendMsgRequest_ChatInfo_ToId() {
  // @@protoc_insertion_point(destructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  SharedDtor();
}

void NewSendMsgRequest_ChatInfo_ToId::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NewSendMsgRequest_ChatInfo_ToId::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NewSendMsgRequest_ChatInfo_ToId::descriptor() {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NewSendMsgRequest_ChatInfo_ToId& NewSendMsgRequest_ChatInfo_ToId::default_instance() {
  protobuf_NewSendMsg_2eproto::InitDefaults();
  return *internal_default_instance();
}

NewSendMsgRequest_ChatInfo_ToId* NewSendMsgRequest_ChatInfo_ToId::New(::google::protobuf::Arena* arena) const {
  NewSendMsgRequest_ChatInfo_ToId* n = new NewSendMsgRequest_ChatInfo_ToId;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NewSendMsgRequest_ChatInfo_ToId::Clear() {
// @@protoc_insertion_point(message_clear_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  if (has_id()) {
    GOOGLE_DCHECK(!id_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*id_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NewSendMsgRequest_ChatInfo_ToId::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  return false;
#undef DO_
}

void NewSendMsgRequest_ChatInfo_ToId::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
}

::google::protobuf::uint8* NewSendMsgRequest_ChatInfo_ToId::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  return target;
}

size_t NewSendMsgRequest_ChatInfo_ToId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional string id = 1;
  if (has_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NewSendMsgRequest_ChatInfo_ToId::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  GOOGLE_DCHECK_NE(&from, this);
  const NewSendMsgRequest_ChatInfo_ToId* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NewSendMsgRequest_ChatInfo_ToId>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
    MergeFrom(*source);
  }
}

void NewSendMsgRequest_ChatInfo_ToId::MergeFrom(const NewSendMsgRequest_ChatInfo_ToId& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_id()) {
    set_has_id();
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
}

void NewSendMsgRequest_ChatInfo_ToId::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewSendMsgRequest_ChatInfo_ToId::CopyFrom(const NewSendMsgRequest_ChatInfo_ToId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewSendMsgRequest_ChatInfo_ToId::IsInitialized() const {
  return true;
}

void NewSendMsgRequest_ChatInfo_ToId::Swap(NewSendMsgRequest_ChatInfo_ToId* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NewSendMsgRequest_ChatInfo_ToId::InternalSwap(NewSendMsgRequest_ChatInfo_ToId* other) {
  id_.Swap(&other->id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NewSendMsgRequest_ChatInfo_ToId::GetMetadata() const {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NewSendMsgRequest_ChatInfo_ToId

// optional string id = 1;
bool NewSendMsgRequest_ChatInfo_ToId::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void NewSendMsgRequest_ChatInfo_ToId::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void NewSendMsgRequest_ChatInfo_ToId::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void NewSendMsgRequest_ChatInfo_ToId::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
const ::std::string& NewSendMsgRequest_ChatInfo_ToId::id() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  return id_.GetNoArena();
}
void NewSendMsgRequest_ChatInfo_ToId::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
#if LANG_CXX11
void NewSendMsgRequest_ChatInfo_ToId::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
#endif
void NewSendMsgRequest_ChatInfo_ToId::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
void NewSendMsgRequest_ChatInfo_ToId::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}
::std::string* NewSendMsgRequest_ChatInfo_ToId::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* NewSendMsgRequest_ChatInfo_ToId::release_id() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void NewSendMsgRequest_ChatInfo_ToId::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId.id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NewSendMsgRequest_ChatInfo::kToIdFieldNumber;
const int NewSendMsgRequest_ChatInfo::kContentFieldNumber;
const int NewSendMsgRequest_ChatInfo::kUnknown2FieldNumber;
const int NewSendMsgRequest_ChatInfo::kUtcFieldNumber;
const int NewSendMsgRequest_ChatInfo::kUnknown3FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NewSendMsgRequest_ChatInfo::NewSendMsgRequest_ChatInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_NewSendMsg_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
}
NewSendMsgRequest_ChatInfo::NewSendMsgRequest_ChatInfo(const NewSendMsgRequest_ChatInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_content()) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.has_toid()) {
    toid_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId(*from.toid_);
  } else {
    toid_ = NULL;
  }
  ::memcpy(&unknown2_, &from.unknown2_,
    reinterpret_cast<char*>(&unknown3_) -
    reinterpret_cast<char*>(&unknown2_) + sizeof(unknown3_));
  // @@protoc_insertion_point(copy_constructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
}

void NewSendMsgRequest_ChatInfo::SharedCtor() {
  _cached_size_ = 0;
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&toid_, 0, reinterpret_cast<char*>(&unknown3_) -
    reinterpret_cast<char*>(&toid_) + sizeof(unknown3_));
}

NewSendMsgRequest_ChatInfo::~NewSendMsgRequest_ChatInfo() {
  // @@protoc_insertion_point(destructor:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  SharedDtor();
}

void NewSendMsgRequest_ChatInfo::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete toid_;
  }
}

void NewSendMsgRequest_ChatInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NewSendMsgRequest_ChatInfo::descriptor() {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NewSendMsgRequest_ChatInfo& NewSendMsgRequest_ChatInfo::default_instance() {
  protobuf_NewSendMsg_2eproto::InitDefaults();
  return *internal_default_instance();
}

NewSendMsgRequest_ChatInfo* NewSendMsgRequest_ChatInfo::New(::google::protobuf::Arena* arena) const {
  NewSendMsgRequest_ChatInfo* n = new NewSendMsgRequest_ChatInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NewSendMsgRequest_ChatInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_content()) {
      GOOGLE_DCHECK(!content_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*content_.UnsafeRawStringPointer())->clear();
    }
    if (has_toid()) {
      GOOGLE_DCHECK(toid_ != NULL);
      toid_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::Clear();
    }
  }
  if (_has_bits_[0 / 32] & 28u) {
    ::memset(&unknown2_, 0, reinterpret_cast<char*>(&unknown3_) -
      reinterpret_cast<char*>(&unknown2_) + sizeof(unknown3_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NewSendMsgRequest_ChatInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_toid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string content = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->content().data(), this->content().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 Unknown2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {
          set_has_unknown2();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unknown2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 utc = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          set_has_utc();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &utc_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 Unknown3 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {
          set_has_unknown3();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unknown3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  return false;
#undef DO_
}

void NewSendMsgRequest_ChatInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->toid_, output);
  }

  // optional string content = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->content(), output);
  }

  // optional int32 Unknown2 = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->unknown2(), output);
  }

  // optional int32 utc = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->utc(), output);
  }

  // optional int32 Unknown3 = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->unknown3(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
}

::google::protobuf::uint8* NewSendMsgRequest_ChatInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->toid_, deterministic, target);
  }

  // optional string content = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->content(), target);
  }

  // optional int32 Unknown2 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->unknown2(), target);
  }

  // optional int32 utc = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->utc(), target);
  }

  // optional int32 Unknown3 = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->unknown3(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  return target;
}

size_t NewSendMsgRequest_ChatInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
  if (has_toid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->toid_);
  }
  // optional string content = 2;
  if (has_content()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  if (_has_bits_[0 / 32] & 28u) {
    // optional int32 Unknown2 = 3;
    if (has_unknown2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->unknown2());
    }

    // optional int32 utc = 4;
    if (has_utc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->utc());
    }

    // optional int32 Unknown3 = 5;
    if (has_unknown3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->unknown3());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NewSendMsgRequest_ChatInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const NewSendMsgRequest_ChatInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NewSendMsgRequest_ChatInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
    MergeFrom(*source);
  }
}

void NewSendMsgRequest_ChatInfo::MergeFrom(const NewSendMsgRequest_ChatInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_content();
      content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_toid()->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::MergeFrom(from.toid());
    }
    if (cached_has_bits & 0x00000004u) {
      unknown2_ = from.unknown2_;
    }
    if (cached_has_bits & 0x00000008u) {
      utc_ = from.utc_;
    }
    if (cached_has_bits & 0x00000010u) {
      unknown3_ = from.unknown3_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void NewSendMsgRequest_ChatInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewSendMsgRequest_ChatInfo::CopyFrom(const NewSendMsgRequest_ChatInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewSendMsgRequest_ChatInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  return true;
}

void NewSendMsgRequest_ChatInfo::Swap(NewSendMsgRequest_ChatInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NewSendMsgRequest_ChatInfo::InternalSwap(NewSendMsgRequest_ChatInfo* other) {
  content_.Swap(&other->content_);
  std::swap(toid_, other->toid_);
  std::swap(unknown2_, other->unknown2_);
  std::swap(utc_, other->utc_);
  std::swap(unknown3_, other->unknown3_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NewSendMsgRequest_ChatInfo::GetMetadata() const {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NewSendMsgRequest_ChatInfo

// required .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.ToId toId = 1;
bool NewSendMsgRequest_ChatInfo::has_toid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void NewSendMsgRequest_ChatInfo::set_has_toid() {
  _has_bits_[0] |= 0x00000002u;
}
void NewSendMsgRequest_ChatInfo::clear_has_toid() {
  _has_bits_[0] &= ~0x00000002u;
}
void NewSendMsgRequest_ChatInfo::clear_toid() {
  if (toid_ != NULL) toid_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::Clear();
  clear_has_toid();
}
const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId& NewSendMsgRequest_ChatInfo::toid() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  return toid_ != NULL ? *toid_
                         : *::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId::internal_default_instance();
}
::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* NewSendMsgRequest_ChatInfo::mutable_toid() {
  set_has_toid();
  if (toid_ == NULL) {
    toid_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId;
  }
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  return toid_;
}
::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* NewSendMsgRequest_ChatInfo::release_toid() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
  clear_has_toid();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* temp = toid_;
  toid_ = NULL;
  return temp;
}
void NewSendMsgRequest_ChatInfo::set_allocated_toid(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo_ToId* toid) {
  delete toid_;
  toid_ = toid;
  if (toid) {
    set_has_toid();
  } else {
    clear_has_toid();
  }
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.toId)
}

// optional string content = 2;
bool NewSendMsgRequest_ChatInfo::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void NewSendMsgRequest_ChatInfo::set_has_content() {
  _has_bits_[0] |= 0x00000001u;
}
void NewSendMsgRequest_ChatInfo::clear_has_content() {
  _has_bits_[0] &= ~0x00000001u;
}
void NewSendMsgRequest_ChatInfo::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_content();
}
const ::std::string& NewSendMsgRequest_ChatInfo::content() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  return content_.GetNoArena();
}
void NewSendMsgRequest_ChatInfo::set_content(const ::std::string& value) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
#if LANG_CXX11
void NewSendMsgRequest_ChatInfo::set_content(::std::string&& value) {
  set_has_content();
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
#endif
void NewSendMsgRequest_ChatInfo::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
void NewSendMsgRequest_ChatInfo::set_content(const char* value, size_t size) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}
::std::string* NewSendMsgRequest_ChatInfo::mutable_content() {
  set_has_content();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* NewSendMsgRequest_ChatInfo::release_content() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
  clear_has_content();
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void NewSendMsgRequest_ChatInfo::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    set_has_content();
  } else {
    clear_has_content();
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.content)
}

// optional int32 Unknown2 = 3;
bool NewSendMsgRequest_ChatInfo::has_unknown2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void NewSendMsgRequest_ChatInfo::set_has_unknown2() {
  _has_bits_[0] |= 0x00000004u;
}
void NewSendMsgRequest_ChatInfo::clear_has_unknown2() {
  _has_bits_[0] &= ~0x00000004u;
}
void NewSendMsgRequest_ChatInfo::clear_unknown2() {
  unknown2_ = 0;
  clear_has_unknown2();
}
::google::protobuf::int32 NewSendMsgRequest_ChatInfo::unknown2() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown2)
  return unknown2_;
}
void NewSendMsgRequest_ChatInfo::set_unknown2(::google::protobuf::int32 value) {
  set_has_unknown2();
  unknown2_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown2)
}

// optional int32 utc = 4;
bool NewSendMsgRequest_ChatInfo::has_utc() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void NewSendMsgRequest_ChatInfo::set_has_utc() {
  _has_bits_[0] |= 0x00000008u;
}
void NewSendMsgRequest_ChatInfo::clear_has_utc() {
  _has_bits_[0] &= ~0x00000008u;
}
void NewSendMsgRequest_ChatInfo::clear_utc() {
  utc_ = 0;
  clear_has_utc();
}
::google::protobuf::int32 NewSendMsgRequest_ChatInfo::utc() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.utc)
  return utc_;
}
void NewSendMsgRequest_ChatInfo::set_utc(::google::protobuf::int32 value) {
  set_has_utc();
  utc_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.utc)
}

// optional int32 Unknown3 = 5;
bool NewSendMsgRequest_ChatInfo::has_unknown3() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void NewSendMsgRequest_ChatInfo::set_has_unknown3() {
  _has_bits_[0] |= 0x00000010u;
}
void NewSendMsgRequest_ChatInfo::clear_has_unknown3() {
  _has_bits_[0] &= ~0x00000010u;
}
void NewSendMsgRequest_ChatInfo::clear_unknown3() {
  unknown3_ = 0;
  clear_has_unknown3();
}
::google::protobuf::int32 NewSendMsgRequest_ChatInfo::unknown3() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown3)
  return unknown3_;
}
void NewSendMsgRequest_ChatInfo::set_unknown3(::google::protobuf::int32 value) {
  set_has_unknown3();
  unknown3_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo.Unknown3)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NewSendMsgRequest::kCntFieldNumber;
const int NewSendMsgRequest::kInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NewSendMsgRequest::NewSendMsgRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_NewSendMsg_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.tencent.mars.sample.proto.NewSendMsgRequest)
}
NewSendMsgRequest::NewSendMsgRequest(const NewSendMsgRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_info()) {
    info_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo(*from.info_);
  } else {
    info_ = NULL;
  }
  cnt_ = from.cnt_;
  // @@protoc_insertion_point(copy_constructor:com.tencent.mars.sample.proto.NewSendMsgRequest)
}

void NewSendMsgRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&info_, 0, reinterpret_cast<char*>(&cnt_) -
    reinterpret_cast<char*>(&info_) + sizeof(cnt_));
}

NewSendMsgRequest::~NewSendMsgRequest() {
  // @@protoc_insertion_point(destructor:com.tencent.mars.sample.proto.NewSendMsgRequest)
  SharedDtor();
}

void NewSendMsgRequest::SharedDtor() {
  if (this != internal_default_instance()) {
    delete info_;
  }
}

void NewSendMsgRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NewSendMsgRequest::descriptor() {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NewSendMsgRequest& NewSendMsgRequest::default_instance() {
  protobuf_NewSendMsg_2eproto::InitDefaults();
  return *internal_default_instance();
}

NewSendMsgRequest* NewSendMsgRequest::New(::google::protobuf::Arena* arena) const {
  NewSendMsgRequest* n = new NewSendMsgRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NewSendMsgRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  if (has_info()) {
    GOOGLE_DCHECK(info_ != NULL);
    info_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::Clear();
  }
  cnt_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NewSendMsgRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 cnt = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_cnt();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cnt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.tencent.mars.sample.proto.NewSendMsgRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.tencent.mars.sample.proto.NewSendMsgRequest)
  return false;
#undef DO_
}

void NewSendMsgRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 cnt = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cnt(), output);
  }

  // optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->info_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.tencent.mars.sample.proto.NewSendMsgRequest)
}

::google::protobuf::uint8* NewSendMsgRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 cnt = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cnt(), target);
  }

  // optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->info_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.tencent.mars.sample.proto.NewSendMsgRequest)
  return target;
}

size_t NewSendMsgRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required int32 cnt = 1;
  if (has_cnt()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cnt());
  }
  // optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
  if (has_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->info_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NewSendMsgRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NewSendMsgRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NewSendMsgRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.tencent.mars.sample.proto.NewSendMsgRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.tencent.mars.sample.proto.NewSendMsgRequest)
    MergeFrom(*source);
  }
}

void NewSendMsgRequest::MergeFrom(const NewSendMsgRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_info()->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::MergeFrom(from.info());
    }
    if (cached_has_bits & 0x00000002u) {
      cnt_ = from.cnt_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void NewSendMsgRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewSendMsgRequest::CopyFrom(const NewSendMsgRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.tencent.mars.sample.proto.NewSendMsgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewSendMsgRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;
  if (has_info()) {
    if (!this->info_->IsInitialized()) return false;
  }
  return true;
}

void NewSendMsgRequest::Swap(NewSendMsgRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NewSendMsgRequest::InternalSwap(NewSendMsgRequest* other) {
  std::swap(info_, other->info_);
  std::swap(cnt_, other->cnt_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NewSendMsgRequest::GetMetadata() const {
  protobuf_NewSendMsg_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_NewSendMsg_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NewSendMsgRequest

// required int32 cnt = 1;
bool NewSendMsgRequest::has_cnt() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void NewSendMsgRequest::set_has_cnt() {
  _has_bits_[0] |= 0x00000002u;
}
void NewSendMsgRequest::clear_has_cnt() {
  _has_bits_[0] &= ~0x00000002u;
}
void NewSendMsgRequest::clear_cnt() {
  cnt_ = 0;
  clear_has_cnt();
}
::google::protobuf::int32 NewSendMsgRequest::cnt() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.cnt)
  return cnt_;
}
void NewSendMsgRequest::set_cnt(::google::protobuf::int32 value) {
  set_has_cnt();
  cnt_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.NewSendMsgRequest.cnt)
}

// optional .com.tencent.mars.sample.proto.NewSendMsgRequest.ChatInfo info = 2;
bool NewSendMsgRequest::has_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void NewSendMsgRequest::set_has_info() {
  _has_bits_[0] |= 0x00000001u;
}
void NewSendMsgRequest::clear_has_info() {
  _has_bits_[0] &= ~0x00000001u;
}
void NewSendMsgRequest::clear_info() {
  if (info_ != NULL) info_->::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::Clear();
  clear_has_info();
}
const ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo& NewSendMsgRequest::info() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  return info_ != NULL ? *info_
                         : *::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo::internal_default_instance();
}
::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* NewSendMsgRequest::mutable_info() {
  set_has_info();
  if (info_ == NULL) {
    info_ = new ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo;
  }
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  return info_;
}
::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* NewSendMsgRequest::release_info() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
  clear_has_info();
  ::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* temp = info_;
  info_ = NULL;
  return temp;
}
void NewSendMsgRequest::set_allocated_info(::com::tencent::mars::sample::proto::NewSendMsgRequest_ChatInfo* info) {
  delete info_;
  info_ = info;
  if (info) {
    set_has_info();
  } else {
    clear_has_info();
  }
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.NewSendMsgRequest.info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sample
}  // namespace mars
}  // namespace tencent
}  // namespace com

// @@protoc_insertion_point(global_scope)
